### ISSUE TITLE
quote 레이아웃 개선

### ISSUE THREAD

**Issue by HyungJu** [teamatus/openNAMU#16]
namu.wiki 에있는 css보시면

```css
.wiki-quote {
	padding:1em calc(2em + 25px) 1em 1em;
	margin:1em 0;
	background:#eeeeee;
	display:table;
	border:2px dashed #ccc;
	border-left:5px solid #71BC6D;
	background-image:url('https://namu.wiki/img/wiki/quote.png?1437660248');
	background-position:calc(100% - 10px) 10px;
	background-repeat:no-repeat;
	background-size:25px;
}
```

이런데 요거 적용해보세요
디자인 개선에 아마도 좋을듯 싶네요

나무위키 이미지를 써도 되는지는 모르겠지만 불가능하면 CC0 image가져아서 쓰면 되니까요

(Hangul input machine is not working correctly now. I' writing korean with google:()
